// Package api provides primitives to interact with the openapi HTTP API.
//
// ErrCode generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for EventType.
const (
	EventTypeEARN  EventType = "EARN"
	EventTypeSPEND EventType = "SPEND"
)

// Defines values for OperationType.
const (
	OperationTypeEARN  OperationType = "EARN"
	OperationTypeSPEND OperationType = "SPEND"
)

// Defines values for RoleCode.
const (
	ADMIN   RoleCode = "ADMIN"
	CASHIER RoleCode = "CASHIER"
	CLIENT  RoleCode = "CLIENT"
)

// Account defines model for Account.
type Account struct {
	BalancePoints int       `json:"balancePoints"`
	CreatedAt     time.Time `json:"createdAt"`
	Id            int64     `json:"id"`

	// LevelCode Business level label (free-form in ruleset)
	LevelCode LevelCode `json:"levelCode"`

	// PublicCode Public code encoded into QR (customer identifier for POS)
	PublicCode PublicCode `json:"publicCode"`

	// TotalSpendMoney Decimal as string to avoid float issues
	TotalSpendMoney string `json:"totalSpendMoney"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// AccessToken JWT access token
	AccessToken string   `json:"accessToken"`
	Account     *Account `json:"account,omitempty"`
	User        User     `json:"user"`
}

// BalanceResponse defines model for BalanceResponse.
type BalanceResponse struct {
	AccountId     int64     `json:"accountId"`
	AsOf          time.Time `json:"asOf"`
	BalancePoints int       `json:"balancePoints"`

	// LevelCode Business level label (free-form in ruleset)
	LevelCode       LevelCode `json:"levelCode"`
	TotalSpendMoney string    `json:"totalSpendMoney"`
}

// CashierAccountSummary defines model for CashierAccountSummary.
type CashierAccountSummary struct {
	AccountId     int64 `json:"accountId"`
	BalancePoints int   `json:"balancePoints"`

	// LevelCode Business level label (free-form in ruleset)
	LevelCode LevelCode `json:"levelCode"`

	// PublicCode Public code encoded into QR (customer identifier for POS)
	PublicCode      PublicCode `json:"publicCode"`
	TotalSpendMoney string     `json:"totalSpendMoney"`
}

// ClientProfile defines model for ClientProfile.
type ClientProfile struct {
	Account Account `json:"account"`
	User    User    `json:"user"`
}

// CreateRulesetRequest defines model for CreateRulesetRequest.
type CreateRulesetRequest struct {
	// BaseRubPerPoint Decimal as string. Must be > 0.
	BaseRubPerPoint string           `json:"baseRubPerPoint"`
	EffectiveFrom   time.Time        `json:"effectiveFrom"`
	Levels          []LevelRuleInput `json:"levels"`
}

// EarnRequest defines model for EarnRequest.
type EarnRequest struct {
	// AmountMoney Decimal as string (money spent)
	AmountMoney string `json:"amountMoney"`

	// OperationId Client-generated idempotency key
	OperationId openapi_types.UUID `json:"operationId"`

	// PublicCode Public code encoded into QR (customer identifier for POS)
	PublicCode PublicCode `json:"publicCode"`

	// Ts Operation timestamp. If omitted, server time is used.
	Ts *time.Time `json:"ts"`
}

// Event defines model for Event.
type Event struct {
	AccountId   int64  `json:"accountId"`
	ActorUserId *int64 `json:"actorUserId"`

	// AmountMoney Present for EARN; decimal as string
	AmountMoney  *string `json:"amountMoney"`
	BalanceAfter int     `json:"balanceAfter"`

	// DeltaPoints Signed delta (+ for EARN, - for SPEND)
	DeltaPoints int       `json:"deltaPoints"`
	Id          int64     `json:"id"`
	RulesetId   *int64    `json:"rulesetId"`
	Ts          time.Time `json:"ts"`
	Type        EventType `json:"type"`
}

// EventType defines model for EventType.
type EventType string

// EventsPage defines model for EventsPage.
type EventsPage struct {
	Items []Event `json:"items"`

	// NextBeforeTs Use as beforeTs for the next page (optional)
	NextBeforeTs *time.Time `json:"nextBeforeTs"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status string `json:"status"`
}

// LevelCode Business level label (free-form in ruleset)
type LevelCode = string

// LevelRule defines model for LevelRule.
type LevelRule struct {
	Id int64 `json:"id"`

	// LevelCode Business level label (free-form in ruleset)
	LevelCode           LevelCode `json:"levelCode"`
	PercentEarn         string    `json:"percentEarn"`
	ThresholdTotalSpend string    `json:"thresholdTotalSpend"`
}

// LevelRuleInput defines model for LevelRuleInput.
type LevelRuleInput struct {
	// LevelCode Business level label (free-form in ruleset)
	LevelCode LevelCode `json:"levelCode"`

	// PercentEarn Percent multiplier as string (e.g., "100.00" = base; "110.00" = +10%). Must be > 0.
	PercentEarn string `json:"percentEarn"`

	// ThresholdTotalSpend Decimal as string. Must be >= 0.
	ThresholdTotalSpend string `json:"thresholdTotalSpend"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`

	// Phone E.164-like phone format (MVP)
	Phone Phone `json:"phone"`
}

// OperationResult defines model for OperationResult.
type OperationResult struct {
	Balance BalanceResponse `json:"balance"`
	Event   Event           `json:"event"`

	// IdempotentReplay true if returned from idempotency cache
	IdempotentReplay *bool              `json:"idempotentReplay,omitempty"`
	OpType           OperationType      `json:"opType"`
	OperationId      openapi_types.UUID `json:"operationId"`
}

// OperationType defines model for OperationType.
type OperationType string

// Phone E.164-like phone format (MVP)
type Phone = string

// Problem defines model for Problem.
type Problem struct {
	// Code Stable machine-readable error code (optional but recommended)
	Code     *string `json:"code,omitempty"`
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// PublicCode Public code encoded into QR (customer identifier for POS)
type PublicCode = string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Password string `json:"password"`

	// Phone E.164-like phone format (MVP)
	Phone Phone `json:"phone"`
}

// RoleCode defines model for RoleCode.
type RoleCode string

// Ruleset defines model for Ruleset.
type Ruleset struct {
	BaseRubPerPoint string      `json:"baseRubPerPoint"`
	CreatedAt       time.Time   `json:"createdAt"`
	EffectiveFrom   time.Time   `json:"effectiveFrom"`
	Id              int64       `json:"id"`
	Levels          []LevelRule `json:"levels"`
}

// RulesetsPage defines model for RulesetsPage.
type RulesetsPage struct {
	Items []Ruleset `json:"items"`
	Total *int      `json:"total"`
}

// SpendRequest defines model for SpendRequest.
type SpendRequest struct {
	AmountPoints int `json:"amountPoints"`

	// OperationId Client-generated idempotency key
	OperationId openapi_types.UUID `json:"operationId"`

	// PublicCode Public code encoded into QR (customer identifier for POS)
	PublicCode PublicCode `json:"publicCode"`

	// Ts Operation timestamp. If omitted, server time is used.
	Ts *time.Time `json:"ts"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        int64     `json:"id"`
	IsActive  bool      `json:"isActive"`

	// Phone E.164-like phone format (MVP)
	Phone Phone      `json:"phone"`
	Roles []RoleCode `json:"roles"`
}

// UsersPage defines model for UsersPage.
type UsersPage struct {
	Items []User `json:"items"`

	// Total Optional total count (may be expensive)
	Total *int `json:"total"`
}

// BeforeTsParam defines model for BeforeTsParam.
type BeforeTsParam = time.Time

// LimitParam defines model for LimitParam.
type LimitParam = int

// Forbidden defines model for Forbidden.
type Forbidden = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// Unauthorized defines model for Unauthorized.
type Unauthorized = Problem

// ValidationError defines model for ValidationError.
type ValidationError = Problem

// GetAdminRulesetsParams defines parameters for GetAdminRulesets.
type GetAdminRulesetsParams struct {
	Limit  *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int        `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetAdminUsersParams defines parameters for GetAdminUsers.
type GetAdminUsersParams struct {
	Limit  *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int        `form:"offset,omitempty" json:"offset,omitempty"`

	// Q Search by phone substring
	Q *string `form:"q,omitempty" json:"q,omitempty"`
}

// GetCashierAccountsByCodePublicCodeEventsParams defines parameters for GetCashierAccountsByCodePublicCodeEvents.
type GetCashierAccountsByCodePublicCodeEventsParams struct {
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// BeforeTs Return events with ts < beforeTs (for pagination)
	BeforeTs *BeforeTsParam `form:"beforeTs,omitempty" json:"beforeTs,omitempty"`
}

// GetMeEventsParams defines parameters for GetMeEvents.
type GetMeEventsParams struct {
	Limit *LimitParam `form:"limit,omitempty" json:"limit,omitempty"`

	// BeforeTs Return events with ts < beforeTs (for pagination)
	BeforeTs *BeforeTsParam `form:"beforeTs,omitempty" json:"beforeTs,omitempty"`
}

// PostAdminRulesetsJSONRequestBody defines body for PostAdminRulesets for application/json ContentType.
type PostAdminRulesetsJSONRequestBody = CreateRulesetRequest

// PostAuthLoginJSONRequestBody defines body for PostAuthLogin for application/json ContentType.
type PostAuthLoginJSONRequestBody = LoginRequest

// PostAuthRegisterJSONRequestBody defines body for PostAuthRegister for application/json ContentType.
type PostAuthRegisterJSONRequestBody = RegisterRequest

// PostCashierEarnJSONRequestBody defines body for PostCashierEarn for application/json ContentType.
type PostCashierEarnJSONRequestBody = EarnRequest

// PostCashierSpendJSONRequestBody defines body for PostCashierSpend for application/json ContentType.
type PostCashierSpendJSONRequestBody = SpendRequest
