name: cd

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare vars
        shell: bash
        run: |
          echo "REPO_LC=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV
          echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}-api:latest
            ghcr.io/${{ env.REPO_LC }}-api:sha-${{ env.SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build & push Frontend (latest + sha)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend/beanefits-ui
          file: ./frontend/beanefits-ui/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ env.REPO_LC }}-frontend:latest
            ghcr.io/${{ env.REPO_LC }}-frontend:sha-${{ env.SHA_SHORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
